### ISSUE TITLE
[Copy Instead Of Share Images] - "Fix" Discord URLs

### ISSUE THREAD

**Issue by hyblocker** [RhythmLunatic/aliucord-plugins#2]
Please consider adding a settings page, which offers a toggle to replace `media.discordapp.net` URLs with `cdn.discordapp.com` URLs upon copying, as some types of media, such as videos, tend to break under the `media` subdomain, and upon replacing the domain with the `cdn` counterpart, they then tend to work.

**Comment by RhythmLunatic** [comment]
Added.
