### ISSUE TITLE
ShowAllTwitterImages won't embed video tweets properly

### ISSUE THREAD

**Issue by nattadasu** [RhythmLunatic/aliucord-plugins#5]
The plugin itself in execution, works properly.

However, when it comes to a tweet with a video, the embed layout changes, so the "video" (more like a thumbnail) will be moved to upper right image field, not buttom.

**Comment by RhythmLunatic** [comment]
This plugin does not modify existing embeds beyond index 0, I think discord changed the embed response on the server side.

**Comment by nattadasu** [comment]
Oof, alright then. Thanks for the explanation!
