### ISSUE TITLE
New Discord update broke a lot of Aliucord plugins, MediaPickerPatch being one of them.

### ISSUE THREAD

**Issue by 0Walker0** [RhythmLunatic/aliucord-plugins#8]
After the newest base Discord apk update the MediaPickerPatch plugin broke.

Even with the plugin enabled it still sends me to the file manager rather then the default gallery app I have (in my case I use Google Photos).  Tried uninstalling/reinstalling both the plugin and Aliucord as a whole, also cleared my cache and none of yhose worked.

**Comment by RhythmLunatic** [comment]
I will try to update the plugins by this weekend, I am currently busy with school/job/updating my Girls' Frontline website for the new event/etc

**Comment by RhythmLunatic** [comment]
It is fixed
